[project]
name = "mon-projet"
version = "0.1.0"
description = "Mon projet Data Science"
requires-python = ">=3.12"
dependencies = [
    "pandas",
    "numpy"
]

[tool.uv]
# Ceci indique à uv de gérer les dépendances