# pyproject.toml

[project]
name = "mon_projet_dev_uv"
version = "0.1.0"
description = "Mon projet de dÃ©veloppement dans Dev Container"
requires-python = ">=3.10"
license = { text = "MIT" }

dependencies = [
    "pandas",
    "numpy",
    "ipython",
    "yfinance",
    "matplotlib"
]
