[project]
name = "my-quant-env"
version = "0.1.0"

# ðŸ‘‡ Hard-code the Python version you want:
requires-python = "==3.10.*"

dependencies = [
  "pandas",
  "yfinance",
  "matplotlib"
  # add more here if you like, e.g.:
  # "numpy",
  # "scipy",
  # "jupyter",
]
